steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cloud-build-experiment:$REVISION_ID', '.' ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment
      - cloud-build-experiment-deployment
      - cloud-build-experiment-container=gcr.io/$PROJECT_ID/cloud-build-experiment:$REVISION_ID
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-experiment'
images:
  - gcr.io/$PROJECT_ID/cloud-build-experiment:$REVISION_ID