steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-build-experiment:${_VERSION_TAG}', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment
      - my-deployment
      - cloud-build-experiment=gcr.io/$PROJECT_ID/cloud-build-experiment:${_VERSION_TAG}
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

images:
  - gcr.io/$PROJECT_ID/cloud-build-experiment:${_VERSION_TAG}

substitutions:
    _VERSION_TAG: latest
